[FEAT] 힌트 예외 처리 강화
Nexters/o-escape-be pull request #44
Opened 2023-07-27 17:42 UTC by delphox60

### PR 타입
- [x] 기능 추가
- [x] 코드 리팩토링

### 반영 브랜치
refactor/hint-error-handling → develop

### 작업 사항
- hint api 요청의 validation 및 error response 를 구현했습니다.
  - 힌트코드 4자리 제한 및 중복 방지
  - 진행률 100 이하 음이 아닌 정수
- 상황 별 error response 구현했습니다..

### 체크리스트
- [x] 빌드에 성공했나요?
- [x] 코드 컨벤션을 잘 지켰나요? (`cmd` + `opt` + `L`)

### 테스트 결과
postman 테스트 결과 이상 없습니다~!

2023-07-28 16:01 UTC, eunsol-an commented on src/main/java/com/nextroom/oescape/dto/HintDto.java
> +    private static final String PROGRESS_REGEX = "(?:[0-9]|[1-9][0-9]|100)";
상수로 처리해서 관리 하기 용이하겠네요! 좋습니다~

2023-07-28 16:20 UTC, eunsol-an requested changes
리뷰 확인 부탁드려요~ 고생하셨습니다!

2023-07-28 16:20 UTC, eunsol-an commented on src/main/java/com/nextroom/oescape/service/HintService.java
> +
힌트 코드의 중복을 검사하는 로직을 추가해주셨네요!
이 로직이 힌트 Entity의 빌드 보다 먼저 오는 게 좋지 않을까요?

2023-07-29 05:14 UTC, delphox60 commented on src/main/java/com/nextroom/oescape/dto/HintDto.java
> +    private static final String PROGRESS_REGEX = "(?:[0-9]|[1-9][0-9]|100)";
별거아니에요 🙈

2023-07-29 05:14 UTC, delphox60 commented on src/main/java/com/nextroom/oescape/service/HintService.java
> +
동의합니다!!
말씀하신 방법대로 수정했어요~!

2023-07-29 05:34 UTC, eunsol-an approved these changes

2023-07-29 05:35 UTC, merged